php artisan make:model ctdonhang
php artisan make:model cthoadonnhap
php artisan make:model ctkho
php artisan make:model dieukhoan
php artisan make:model donhang
php artisan make:model giamgia
php artisan make:model giasanpham
php artisan make:model gioithieu
php artisan make:model hoadonnhap
php artisan make:model kho
php artisan make:model lienhe
php artisan make:model loaisanpham
php artisan make:model menu
php artisan make:model nguoidung
php artisan make:model nhacungcap
php artisan make:model nhasanxuat
php artisan make:model phuongthucthanhtoan
php artisan make:model quyen
php artisan make:model sanpham
php artisan make:model slide
php artisan make:model thongso
php artisan make:model tintuc
php artisan make:model GioHang